config/routes.rb
Rails.application.routes.draw do
    devise_for :admins, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
    devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

    namespace :admin do
      get '/' => 'homes#top'
      resources :customers,   only: %i(index show edit update create destroy)
      resources :diarys,      only: %i(index destroy)
    end

    scope module: :public do
        root :to                             =>  'homes#top'
        get    '/about'                      =>  'homes#about'
        get    'customers/withdraw_confirm'  =>  'customers#withdraw_confirm'
        patch  'customers/withdraw'          =>  'customers#withdraw'
        get    'customers/information/edit',             to: 'customers#edit', as: 'edit_customer'
        patch  'customers/information',      to: 'customers#update', as: 'update_customer'
      resources :diarys do
        resources :comments, only: %i(create destroy)
        resource :favorites, only: %i(create destroy)
      end

      resources :customers,  only: %i(show edit update index ) do
        member do
        get 'favorites' , to: 'customers#favorite'
        end
        resource :relationships, only: %i(create destroy)
        get 'followings' => 'relationships#followings', as: 'followings'
        get 'followers' => 'relationships#followers', as: 'followers'
      end

      get    'searchs/search'             =>  'searchs#search'
      post '/guests/guest_sign_in', to: 'guests#new_guest'
      resources :sentiments,      only: %i(create destroy)

      # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    # 会員の一覧
    @customers = Customer.all.page(params[:page]).per(20)
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="container-md">
  <h1>会員一覧</h1>
  <table class ="table">
    <tr bgcolor="#BFC5CA">
      <td>会員ID</td>
      <td>氏名</td>
      <td>メールアドレス</td>
      <td>ステータス</td>
    </tr>
    <% @customers.each do |customer| %>
      <% unless customer.guest? %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= link_to admin_customer_path(customer) do %><%= customer.full_name %><% end %></td>
        <td><%= customer.email %></td>
        <!--会員ステータスを表示するための記述-->
        <td>
          <% if customer.is_deleted == "exist" %>
            <p style = "color: #4ec51e;">有効</p>
          <% else %>
            <p style = "color: #ff3838;">退会</p>
          <% end %>
        </td>
      </tr>
      <% end %>
    <% end %>
  </table>
</dev>