config/routes.rb
Rails.application.routes.draw do
    devise_for :admins, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
    devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

    namespace :admin do
      get '/' => 'homes#top'
      resources :customers,   only: %i(index show edit update create destroy)
      resources :diarys,      only: %i(index destroy)
    end

    scope module: :public do
        root :to                             =>  'homes#top'
        get    '/about'                      =>  'homes#about'
        get    'customers/withdraw_confirm'  =>  'customers#withdraw_confirm'
        patch  'customers/withdraw'          =>  'customers#withdraw'
        get    'customers/information/edit',             to: 'customers#edit', as: 'edit_customer'
        patch  'customers/information',      to: 'customers#update', as: 'update_customer'
      resources :diarys do
        resources :comments, only: %i(create destroy)
        resource :favorites, only: %i(create destroy)
      end

      resources :customers,  only: %i(show edit update index ) do
        member do
        get 'favorites' , to: 'customers#favorite'
        end
        resource :relationships, only: %i(create destroy)
        get 'followings' => 'relationships#followings', as: 'followings'
        get 'followers' => 'relationships#followers', as: 'followers'
      end

      get    'searchs/search'             =>  'searchs#search'
      post '/guests/guest_sign_in', to: 'guests#new_guest'
      resources :sentiments,      only: %i(create destroy)

      # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    end
end

app/views/layouts/_error_messages.html.erb
<% if object.present? && object.errors.any? %>
      <%= object.errors.count %>件のエラーが発生しました
  <ul>
      <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <!--ヘッダーの色の指定-->
  <nav class="navbar navbar-expand-lg navbar-light", style="
              background: -webkit-linear-gradient(-101deg, rgb(206, 71, 71), rgb(211, 216, 201));
              background: linear-gradient(-101deg, rgb(206, 71, 71), rgb(211, 216, 201));">

    <div class="container-fluid">
      <!--<div class="row w-100">-->
      <!--    <div class="col-3">-->
            <!--ここにロゴが入ります-->
          <%= link_to image_tag("top-logo.png", class: "top_hedder_logo"), root_path %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          </div>
          <div class="col-9">
          <div class="row w-100 justify-content-end">

            <!--ドロップダウンの記述-->
            <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">

              <ul class="navbar-nav ml-auto">
                <% if customer_signed_in? %>
                  <!--Customer ログイン後header-->
                  <span class="navbar-text text-right mr-3">ようこそ、<%= current_customer.full_name %>さん</span>
                  <li><%= link_to customer_path(current_customer),data: {"turbolinks": false}, class: 'nav-link text-right' do%>
                  <i class="fa-solid fa-house-flag"></i>mypage
                  <% end %>
                  </li>
                  <li><%= link_to diarys_path, class: 'nav-link text-right' do%>
                  <i class="fa-solid fa-book-open-reader"></i>diarys
                  <% end %>
                  </li>
                   <li><%= link_to customers_path, class: 'nav-link text-right' do%>
                   <i class="fa-solid fa-users"></i> users
                   <% end %>
                   </li>
                  <li><%= button_to destroy_customer_session_path, class: 'nav-link text-right', method: :delete do%>
                  <i class="fa-solid fa-right-from-bracket"></i>logout
                  <% end %>
                  </li>
                <% elsif admin_signed_in? %>
                  <!--Admin ログイン後header-->
                  <li><%= link_to admin_path, class: 'nav-link text-right' do%>
                  <i class="fa-solid fa-users"></i> users
                  <% end %>
                  </li>
                  <li><%= link_to "ログアウト",   destroy_admin_session_path,      class: ' nav-link text-right', method: :delete do%>
                  <i class="fa-solid fa-right-from-bracket"></i>logout
                  <% end %>
                  </li>
                <% else %>
                  <!--共通ログイン前 header-->
                  <li><%= link_to about_path, class: 'nav-link text-right' do %>
                        <i class="fa-solid fa-house-flag"></i> about
                      <% end %>
                  </li>
                  <li><%= link_to diarys_path, class: 'nav-link text-right' do%>
                      <i class="fa-solid fa-book-open-reader"></i> 投稿一覧
                      <% end %>
                  </li>
                  <li><%= link_to new_customer_registration_path, class: 'nav-link text-right' do%>
                      <i class="fa-solid fa-circle-plus"></i>新規登録
                      <% end %>
                  </li>
                  <li><%= link_to new_customer_session_path,       class: 'nav-link text-right' do%>
                        <i class="fa-solid fa-right-to-bracket"></i> ログイン
                      <% end %>
                  </li>
                  <li><%= link_to 'ゲストログイン（閲覧用）', public_guest_sign_in_path, class: "btn btn-danger btn-sm btn-block mb-3 sign_in", method: :post %></li>
                <% end %>
                <div class="search_form serch_inner">
                  <%= render 'public/searchs/form' %>
                </div>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tuning2</title>

    <!--<meta name="viewport" content="width=device-width,initial-scale=1">-->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/61009a7efc.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vivus/0.3.2/vivus.js"></script>


    <!--ブートストラップ読み込み-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/move02/9-4-1/css/reset.css">
    <link rel="stylesheet" type="text/css" href="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/move02/9-4-1/css/9-4-1.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">

    <!--フォントの変更-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Catamaran:wght@100&family=Lobster&family=Zen+Maru+Gothic:wght@700&family=Zen+Old+Mincho&display=swap" rel="stylesheet">

    <!--どこで管理するか-->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
    <%= yield %>
    </main>

  </body>
</html>